/* Autogenerated by /usr/bin/halcompile on Tue Nov 23 11:20:05 2021 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:servo_tuning:");
MODULE_INFO(linuxcnc, "pin:in-1:s32:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:in-2:s32:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:scale:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:reset-offset:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:out:float:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:out-ddt1:float:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:out-ddt2:float:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:out-ddt12:float:0:out::None:None");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_s32_t *in_1;
    hal_s32_t *in_2;
    hal_float_t *scale;
    hal_bit_t *reset_offset;
    hal_float_t *out;
    hal_float_t *out_ddt1;
    hal_float_t *out_ddt2;
    hal_float_t *out_ddt12;
    double in_1_lst;

    double in_2_lst;

    double offset;

};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_s32_newf(HAL_IN, &(inst->in_1), comp_id,
        "%s.in-1", prefix);
    if(r != 0) return r;
    r = hal_pin_s32_newf(HAL_IN, &(inst->in_2), comp_id,
        "%s.in-2", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->scale), comp_id,
        "%s.scale", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->reset_offset), comp_id,
        "%s.reset-offset", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->out), comp_id,
        "%s.out", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->out_ddt1), comp_id,
        "%s.out-ddt1", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->out_ddt2), comp_id,
        "%s.out-ddt2", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->out_ddt12), comp_id,
        "%s.out-ddt12", prefix);
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
int rtapi_app_main(void) {
    int r = 0;
    comp_id = hal_init("servo_tuning");
    if(comp_id < 0) return comp_id;
    r = export("servo-tuning", 0);
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef in_1
#define in_1 (0+*__comp_inst->in_1)
#undef in_2
#define in_2 (0+*__comp_inst->in_2)
#undef scale
#define scale (0+*__comp_inst->scale)
#undef reset_offset
#define reset_offset (0+*__comp_inst->reset_offset)
#undef out
#define out (*__comp_inst->out)
#undef out_ddt1
#define out_ddt1 (*__comp_inst->out_ddt1)
#undef out_ddt2
#define out_ddt2 (*__comp_inst->out_ddt2)
#undef out_ddt12
#define out_ddt12 (*__comp_inst->out_ddt12)
#undef in_1_lst
#define in_1_lst (__comp_inst->in_1_lst)
#undef in_2_lst
#define in_2_lst (__comp_inst->in_2_lst)
#undef offset
#define offset (__comp_inst->offset)


#line 18 "servo_tuning.comp"
#include "rtapi_math.h"

#
FUNCTION(_) 
 {
    double var1 = ((double)in_1 / scale);
    double var2 = ((double)in_2 / scale);
    if(reset_offset) {offset = var1 - var2;};
    var2 = var2 + offset;   
    out = var1 - var2;
    out_ddt1 = (var1 - in_1_lst) / fperiod;
    out_ddt2 = (var2 - in_2_lst) / fperiod;
    out_ddt12 = out_ddt1 - out_ddt2;
    in_1_lst = var1; 
    in_2_lst = var2;
 }


static int __comp_get_data_size(void) { return 0; }
